
trigger:
- main

pool: Self-Hosted-Pool

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Use Python 3.9'

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade build setuptools twine
    python setup.py sdist bdist_wheel
  displayName: 'Install dependencies'
  
- task: TwineAuthenticate@1
  inputs:
    artifactFeed: ado-python-wheel-feed

- script: |
    twine upload -r ado-wheel-pkg-feed --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Push to Artifacts'
